class FarmerDetailsModel {
  String farmerId;
  String applicationNo;
  String siteSurveyStatus;
  String dispatchStatus;
  String assetMappingStatus;
  String iAndCStatus;
  String isIcCompleted;
  String statusName;
  String siteSurveyPhoto;
  String consentFormPhoto;
  String declarationFormPhoto;
  String landPaperPhoto;
  String foundationPhoto;
  String structurePhoto;
  String solarPvPhoto;
  String installationPhoto;
  String dispatchReceiptPhoto;
  String applicantType;
  String projectId;
  String projectName;
  String sanctionId;
  String sanctionName;
  String sanctionYear;
  String tenderId;
  String tenderName;
  String vendorId;
  String vendorName;
  String farmerName;
  String fatherName;
  String mobile;
  String email;
  String gender;
  String farmerCategory;
  String locStateId;
  String locState;
  String locDistrictId;
  String locDistrict;
  String locTehsilId;
  String locTehsil;
  String locVillageId;
  String locVillage;
  String locOtherVillage;
  String locBlockId;
  String locBlock;
  String surveyNo1;
  String surveyNo2;
  String latitude;
  String longitude;
  String irrigationMode;
  String waterDepthFt;
  String sourceOfWater;
  String sizeBoreWell;
  String havingElectric;
  String southFacing;
  String sourceOfPower;
  String siteSuitable;
  String remarks;
  String pumpCapacity;
  String pumpType;
  String pumpSubType;
  String pumpCategory;
  String pumpController;
  String headOfPumpMeter;
  String spvCapacity;
  String landCoverage;
  String totalPumpCost;
  String rateCartId;
  String statePumpCost;
  String centralPumpCost;
  String farmerPumpCost;
  String isFoundation;

  FarmerDetailsModel({
    required this.farmerId,
    required this.applicationNo,
    required this.siteSurveyStatus,
    required this.dispatchStatus,
    required this.assetMappingStatus,
    required this.iAndCStatus,
    required this.isIcCompleted,
    required this.statusName,
    required this.siteSurveyPhoto,
    required this.consentFormPhoto,
    required this.declarationFormPhoto,
    required this.landPaperPhoto,
    required this.foundationPhoto,
    required this.structurePhoto,
    required this.solarPvPhoto,
    required this.installationPhoto,
    required this.dispatchReceiptPhoto,
    required this.applicantType,
    required this.projectId,
    required this.projectName,
    required this.sanctionId,
    required this.sanctionName,
    required this.sanctionYear,
    required this.tenderId,
    required this.tenderName,
    required this.vendorId,
    required this.vendorName,
    required this.farmerName,
    required this.fatherName,
    required this.mobile,
    required this.email,
    required this.gender,
    required this.farmerCategory,
    required this.locStateId,
    required this.locState,
    required this.locDistrictId,
    required this.locDistrict,
    required this.locTehsilId,
    required this.locTehsil,
    required this.locVillageId,
    required this.locVillage,
    required this.locOtherVillage,
    required this.locBlockId,
    required this.locBlock,
    required this.surveyNo1,
    required this.surveyNo2,
    required this.latitude,
    required this.longitude,
    required this.irrigationMode,
    required this.waterDepthFt,
    required this.sourceOfWater,
    required this.sizeBoreWell,
    required this.havingElectric,
    required this.southFacing,
    required this.sourceOfPower,
    required this.siteSuitable,
    required this.remarks,
    required this.pumpCapacity,
    required this.pumpType,
    required this.pumpSubType,
    required this.pumpCategory,
    required this.pumpController,
    required this.headOfPumpMeter,
    required this.spvCapacity,
    required this.landCoverage,
    required this.totalPumpCost,
    required this.rateCartId,
    required this.statePumpCost,
    required this.centralPumpCost,
    required this.farmerPumpCost,
    required this.isFoundation,
  });

  factory FarmerDetailsModel.fromJson(Map<String, dynamic> json) {
    return FarmerDetailsModel(
      farmerId: json['farmer_id'],
      applicationNo: json['application_no'],
      siteSurveyStatus: json['site_survey_status'],
      dispatchStatus: json['dispatch_status'],
      assetMappingStatus: json['asset_mapping_status'],
      iAndCStatus: json['i_and_c_status'],
      isIcCompleted: json['is_ic_complated'],
      statusName: json['status_name'],
      siteSurveyPhoto: json['site_survey_photo'],
      consentFormPhoto: json['consent_form_photo'],
      declarationFormPhoto: json['declaration_form_photo'],
      landPaperPhoto: json['land_paper_photo'],
      foundationPhoto: json['foundation_photo'],
      structurePhoto: json['structure_photo'],
      solarPvPhoto: json['solarpv_photo'],
      installationPhoto: json['installation_photo'],
      dispatchReceiptPhoto: json['dispatchreceipt_photo'],
      applicantType: json['applicant_type'],
      projectId: json['project_id'],
      projectName: json['project_name'],
      sanctionId: json['sanction_id'],
      sanctionName: json['sanction_name'],
      sanctionYear: json['sanction_year'],
      tenderId: json['tender_id'],
      tenderName: json['tender_name'],
      vendorId: json['vendor_id'],
      vendorName: json['vendor_name'],
      farmerName: json['farmer_name'],
      fatherName: json['father_name'],
      mobile: json['mobile'],
      email: json['email'],
      gender: json['gender'],
      farmerCategory: json['farmer_category'],
      locStateId: json['loc_state_id'],
      locState: json['loc_state'],
      locDistrictId: json['loc_district_id'],
      locDistrict: json['loc_district'],
      locTehsilId: json['loc_tehsil_id'],
      locTehsil: json['loc_tehsil'],
      locVillageId: json['loc_village_id'],
      locVillage: json['loc_village'],
      locOtherVillage: json['loc_other_village'],
      locBlockId: json['loc_block_id'],
      locBlock: json['loc_block'],
      surveyNo1: json['survey_no_1'],
      surveyNo2: json['survey_no_2'],
      latitude: json['latitude'],
      longitude: json['longitude'],
      irrigationMode: json['irrigation_mode'],
      waterDepthFt: json['water_depth_ft'],
      sourceOfWater: json['source_of_water'],
      sizeBoreWell: json['size_bore_well'],
      havingElectric: json['having_electric'],
      southFacing: json['south_facing'],
      sourceOfPower: json['source_of_power'],
      siteSuitable: json['site_suitable'],
      remarks: json['remarks'],
      pumpCapacity: json['pump_capacity'],
      pumpType: json['pump_type'],
      pumpSubType: json['pump_subtype'],
      pumpCategory: json['pump_category'],
      pumpController: json['pump_controller'],
      headOfPumpMeter: json['head_of_pump_meter'],
      spvCapacity: json['spv_capacity'],
      landCoverage: json['land_coverage'],
      totalPumpCost: json['total_pump_cost'],
      rateCartId: json['rate_cart_id'],
      statePumpCost: json['state_pump_cost'],
      centralPumpCost: json['central_pump_cost'],
      farmerPumpCost: json['farmer_pump_cost'],
      isFoundation: json['is_foundation'],
    );
  }
}