// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBktLZMKUUDusvJxg0a79fZ6iZrkvCS7A0',
    appId: '1:127248413518:web:7853719694499d443e241f',
    messagingSenderId: '127248413518',
    projectId: 'oswal-pump-8d88d',
    authDomain: 'oswal-pump-8d88d.firebaseapp.com',
    storageBucket: 'oswal-pump-8d88d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD69IPEAry9PFd5d4PV_Zu_yNwvx2GfEVE',
    appId: '1:127248413518:android:cfffd12dd3d184343e241f',
    messagingSenderId: '127248413518',
    projectId: 'oswal-pump-8d88d',
    storageBucket: 'oswal-pump-8d88d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaoK1S_aWQu5QggCcND72XRkdkap2hkBk',
    appId: '1:127248413518:ios:28a524afdb04b7c63e241f',
    messagingSenderId: '127248413518',
    projectId: 'oswal-pump-8d88d',
    storageBucket: 'oswal-pump-8d88d.appspot.com',
    iosBundleId: 'com.solar.oswal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaoK1S_aWQu5QggCcND72XRkdkap2hkBk',
    appId: '1:127248413518:ios:28a524afdb04b7c63e241f',
    messagingSenderId: '127248413518',
    projectId: 'oswal-pump-8d88d',
    storageBucket: 'oswal-pump-8d88d.appspot.com',
    iosBundleId: 'com.solar.oswal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBktLZMKUUDusvJxg0a79fZ6iZrkvCS7A0',
    appId: '1:127248413518:web:491cdd3bb519de4d3e241f',
    messagingSenderId: '127248413518',
    projectId: 'oswal-pump-8d88d',
    authDomain: 'oswal-pump-8d88d.firebaseapp.com',
    storageBucket: 'oswal-pump-8d88d.appspot.com',
  );
}
